---
title: "Introduction to R"
author: "Nicholas"
date: "5/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Data Manipulation

  # Glimpse the counties table
glimpse(counties)

counties %>%
  # Select the columns
  select(state,county,population,poverty)
  
counties_selected %>%
  # Add a verb to sort in descending order of public_work
  arrange(desc(public_work))

counties_selected %>%
  # Filter for counties with a population above 1000000
  filter(state == "California",
         population > 1000000)
         
counties_selected %>%
  # Add a new column public_workers with the number of people employed in public work
  mutate(public_workers = public_work * population / 100) %>%
  # Sort in descending order of the public_workers column
  arrange(desc(public_workers))

counties_selected <- counties %>%
  select(county, region, state, population, citizens)  
  # Use count to find the number of counties in each region
counties_selected %>%
  count(region, sort = TRUE)
  # Find number of counties per state, weighted (wt) by citizens, sorted in descending order
counties_selected %>%
  count(state, wt = citizens, sort = TRUE)
  
counties_selected %>%
  # Group by region
  group_by(region) %>%
  # Find the greatest number of citizens who walk to work
  top_n(1,walk) # column of interest goes second, and the number of rows you're grabbing goes first.
  
counties_selected %>%
  # Find the total population for each combination of state and metro
  group_by(state, metro) %>%
  summarize(total_pop = sum(population)) %>%
  # Extract the most populated row for each state
  top_n(1, total_pop) %>%
  # Count the states with more people in Metro or Nonmetro areas
  ungroup() %>% 
  count(metro)
  
counties %>%
  # Select the state, county, population, and those ending with "work"
  select(state,county,population,ends_with("work")) %>%
  # Filter for counties that have at least 50% of people engaged in public work
  filter(public_work>50)

counties %>%
  # Count the number of counties in each state
  count(state) %>%
  # Rename the n column to num_counties
  rename(num_counties = n)

counties %>%
  # Select state, county, and poverty as poverty_rate
  select(state, county, poverty_rate = poverty)

transmute() is a combination of select and mutate
counties %>%
  # Keep the state, county, and populations columns, and add a density column
  transmute(state, county, population, density = population / land_area) %>%
  # Filter for counties with a population greater than one million 
  filter(population > 1000000) %>%
  # Sort density in ascending order 
  arrange(density)
  
  # Change the name of the unemployment column
counties %>%
  rename(unemployment_rate = unemployment)

  # Keep the state and county columns, and the columns containing poverty
counties %>%
  select(state, county, contains("poverty"))

  # Calculate the fraction_women column without dropping the other columns
counties %>%
  mutate(fraction_women = women / population)

  # Keep only the state, county, and employment_rate columns
counties %>%
  transmute(state, county, employment_rate = employed / population)