---
title: "Introduction to R"
author: "Nicholas"
date: "5/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Data Joining

### Inner Join

parts %>% 
  # by creates the join condition of the respective table
  # suffix adds a suffix to the variable name of the respective table
  inner_join(part_categories, by = c("part_cat_id" = "id"), suffix = c("_part", "_category"))
  
  # joining multiple tables
sets %>%
  # Add inventories using an inner join 
  inner_join(inventories,by=c("set_num"="set_num")) %>%
  # Add inventory_parts using an inner join 
  inner_join(inventory_parts,by=c("id"="inventory_id"))

### Left Join / Right Join
  # Combine the star_destroyer and millennium_falcon tables
millennium_falcon %>%
  left_join(star_destroyer,by=c("part_num","color_id"),suffix=c("_falcon","_star_destroyer"))
  
  # Left join the Millennium Falcon colors to the Star Destroyer colors
millennium_falcon_colors %>%
  left_join(star_destroyer_colors,by="color_id",suffix=c("_falcon","_star_destroyer"))
  
### Joining tables with themselves to establish parent child relationship
themes %>% 
  # Inner join the themes table
  inner_join(themes, by = c("id" = "parent_id"), suffix = c("_parent", "_child"))
  
### Full Joins
batman_parts %>%
  # Combine the star_wars_parts table 
  full_join(star_wars_parts, by = c("part_num", "color_id"), suffix = c("_batman", "_star_wars")) %>%
  # Replace NAs with 0s in the n_batman and n_star_wars columns 
  replace_na(list(n_batman = 0, n_star_wars = 0))

### Semi Joins
filter the first table for observations that match the second
  # Filter the batwing set for parts that are also in the batmobile set
  batwing %>%
    semi_join(batmobile, by="part_num")
  # Use inventory_parts to find colors included in at least one set
  colors %>%
    semi_join(inventory_parts,by=c("id"="color_id"))

### Anti Joins
filter the first table for observations that don't match the second
  # Filter the batwing set for parts that aren't in the batmobile set
  batwing %>%
    anti_join(batmobile, by="part_num")
    
    
### Binding Tables
Binding is simply adding rows together. The mutate creates a new column that act as an identifier to the original source table

  # Combine the two tables into posts_with_tags
posts_with_tags <- bind_rows(questions_with_tags %>% mutate(type = "question"),
                              answers_with_tags %>% mutate(type = "answer"))